const links=[...document.querySelectorAll("nav a")],sections=[...document.querySelectorAll("main section")];let catalog={exercises:[],incidents:[]},apiAvailable=true;
const observer=new IntersectionObserver(entries=>{entries.filter(entry=>entry.isIntersecting).forEach(entry=>links.forEach(link=>link.classList.toggle("active",link.hash===`#${entry.target.id}`)));},{rootMargin:"-20% 0px -65%"});sections.forEach(section=>observer.observe(section));
const esc=value=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function api(path,options={}){const response=await fetch(path,{headers:{"content-type":"application/json"},...options});if(!response.ok)throw new Error("Operations service unavailable");return response.json();}
async function load(){try{const [exercises,incidents]=await Promise.all([api("/api/labs"),api("/api/incidents")]);catalog={exercises,incidents};}catch{apiAvailable=false;catalog=await fetch("../data/labs.json").then(response=>response.json());}}
function renderLabs(query=""){const q=query.toLowerCase(),items=catalog.exercises.filter(item=>JSON.stringify(item).toLowerCase().includes(q));document.querySelector(".runbook-list").innerHTML=items.map((item,index)=>`<details ${index===0?"open":""}><summary><span>${item.id.replace("LAB-","")}</span><div><small>${esc(item.track.toUpperCase())} / ${item.duration} MIN / ${esc(item.difficulty.toUpperCase())}</small><strong>${esc(item.title)}</strong></div><b>+</b></summary><div class="runbook-body"><ol><li><b>Objective:</b> ${esc(item.objective)}</li><li>Capture the baseline and required approval.</li><li>Execute the bounded change shown below.</li><li><b>Validation:</b> ${esc(item.validation)}</li><li>Record evidence, rollback status, and owner handoff.</li></ol><pre><code>${esc(item.command)}</code><button data-copy>Copy command</button></pre><button class="record-run" data-run="${esc(item.id)}">Record validated run</button></div></details>`).join("");bindDetails();}
function renderIncidents(){const table=document.querySelector(".issue-table");table.innerHTML=`<div class="thead"><span>ISSUE</span><span>ROOT CAUSE</span><span>FIX + VERIFICATION</span><span>STATUS</span></div>${catalog.incidents.map(item=>`<div><strong><small>${item.id}</small>${esc(item.symptom)}</strong><span>${esc(item.rootCause)}</span><span>${esc(item.fix)}</span><b>RESOLVED</b></div>`).join("")}`;}
function bindDetails(){document.querySelectorAll("details").forEach(detail=>detail.addEventListener("toggle",()=>{detail.querySelector("summary>b").textContent=detail.open?"−":"+";}));document.querySelectorAll("[data-copy]").forEach(button=>button.addEventListener("click",async()=>{await navigator.clipboard?.writeText(button.previousElementSibling.textContent);button.textContent="Copied";setTimeout(()=>button.textContent="Copy command",1000);}));document.querySelectorAll("[data-run]").forEach(button=>button.addEventListener("click",async()=>{const payload={labId:button.dataset.run,operator:"Paul Revanth",status:"Validated",evidence:"Procedure completed; stated validation result recorded"};if(apiAvailable){try{const run=await api("/api/runs",{method:"POST",body:JSON.stringify(payload)});button.textContent=`Run #${run.id} recorded ✓`;}catch{button.textContent="Could not record";}}else{const runs=JSON.parse(localStorage.getItem("cloud-lab-runs")||"[]");runs.push({...payload,at:new Date().toISOString()});localStorage.setItem("cloud-lab-runs",JSON.stringify(runs));button.textContent="Local run recorded ✓";}}));}
document.querySelector("#menu").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));links.forEach(link=>link.addEventListener("click",()=>document.querySelector(".sidebar").classList.remove("open")));
const search=document.createElement("input");search.className="lab-search";search.type="search";search.placeholder="Search 30 exercises by skill, command, or outcome";document.querySelector("#runbooks>p:nth-of-type(2)").after(search);search.addEventListener("input",event=>renderLabs(event.target.value));
await load();renderLabs();renderIncidents();document.querySelector(".version").textContent=`DOCUMENTATION · ${catalog.exercises.length} LABS · ${catalog.incidents.length} INCIDENTS`;
